# Natural Language Processing

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [12]:
import pandas as pd
file_name = 'sample_data_complaint.xlsx' 
dataset = pd.read_excel(file_name)
print(dataset.head())

   S No  ... Is it required to report to Authorities
0     1  ...                                      No
1     2  ...                                      No
2     3  ...                                      No
3     4  ...                                      No
4     5  ...                                      No

[5 rows x 5 columns]


## Cleaning the texts

In [18]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 100):
  review = re.sub('[^a-zA-Z]', ' ', dataset['Complaint Text'][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [19]:
print(corpus)

['leakag observ use alin seri concentr wash buffer', 'custom indic product shipment receiv warm temperatur stress therefor not suitabl use', 'shipment architect concentr wash buffer list number c lot number fn damag transit fedex refus custom', 'alin ci seri system softwar v scm westgard rule trigger two version assay instal instrument', 'custom observ bottl appear distend use architect concentr wash buffer kit', 'custom observ activ read failur error code use architect reaction vessel rv', 'custom observ microparticl bottl contain mold type deposit use architect intact pth reagent', 'custom report observ fals elev ldl hdl result patient use direct ldl reagent ln e ultra hdl reagent ln k architect system sum ldl hdl result patient greater total cholesterol result', 'custom observ multipl level non abbott control shift high use architect bnp calibr', 'assay packag insert not download system abbott mail inbox configur receiv insert norwegian languag text state assay insert english langua

## Creating the Bag of Words model

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, 2].values

## Splitting the dataset into the Training set and Test set

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.10, random_state = 0)

## Training the Naive Bayes model on the Training set

In [41]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train.astype(str))

GaussianNB(priors=None, var_smoothing=1e-09)

## Predicting the Test set results

In [38]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['No' 'No']
 ['No' 'Yes']
 ['No' 'No']
 ['No' 'Yes']
 ['No' 'Yes']
 ['No' 'No']
 ['No' 'No']
 ['No' 'No']
 ['No' nan]
 ['No' 'No']]


## Making the Confusion Matrix

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test.astype(str), y_pred)
print(cm)
accuracy_score(y_test.astype(str), y_pred)

[[6 0 0]
 [3 0 0]
 [1 0 0]]


0.6